### PR TITLE
From CDN to SDK

### PR DESCRIPTION
**Pull request by YU000jp**
I read your comment on https://discuss.logseq.com/t/how-to-create-settings-page/12402.

Animation6w11

I'm sorry if my thoughts differ from yours. Using the `SDK` (node.js) made it possible to use the setting UI.
Is it ok to use node.js? I set it up to work with the `SDK` instead of the `CDN`.

CDN: https://github.com/hankhank10/i-listened-plugin/blob/061f8a2a2fe17a9fa174ddaf32c4ba2bcef5087e/index.html#L5
SDK: @logseq/libs

Here's how to edit the plugin.  If you don't want to use node.js, that was my nosy.🙇‍♂️🙇

## Required environment
1. GitHub desktop client https://desktop.github.com/
1. Visual Studio Code https://azure.microsoft.com/ja-jp/products/visual-studio-code/
1. node.js https://pnpm.io/ja/cli/env

## Step
 1. Launch Visual Studio Code at the plugin folder
 2. Launch a terminal by contextmenu from the same folder as the repository. 
 3. Run command `npm install -g pnpm`
 4. Run command `pnpm install`
 5. Modules is installed and the development environment is ready.
 6. Edit the main script `src/index.js`
 7. Build the plugin. Run command `pnpm build`
 8. Have Logseq load the plugin in developer mode.
 9. repeat 6-8
Animation6w12

### CODE REVIEW

**Comment by hankhank10** [comment]
Thank you so much @YU000jp for this incredibly helpful PR

**Comment by hankhank10** [comment]
@YU000jp , I have now finished this plugin. I would love it if you could test it before I publish to the marketplace.

**Comment by YU000jp** [comment]
It works fine as a plugin, but I ran into a server-side issue.

on Logseq, slash command /spotify.....

image


I did the authentication once on the server side and got an error.

image


Animation6w12

**Comment by hankhank10** [comment]
Thank you @YU000jp. I believe I have now fixed the server-side issue. Could you possibly test again please?

**Comment by YU000jp** [comment]
return same situation
Animation6w12

Maybe it's a CORS error.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors

**Comment by hankhank10** [comment]
Thank you - could you let me know what URL is showing the error please? Also would you mind trying in a incognito browser please? I can't replicate the error on any of my devices.

**Comment by YU000jp** [comment]
https://spotify.logspot.top/callback/?code=AQDEASQIYoU56JGqffbZSTwM_dggmvXG3at8Wgk6j5AXnnlohaWkNZIH1_QKFMVs7DKfFkY5XXFV_PrK7p96G5VSmoHkUHjaGlYQ0HJXSQe7V3FFk3DrZp0Q3C-CM1OcfzGphLiJcFnLSScMYbM8HKQcjuXjAuXma-c-9Y0CfRPKhHT-3pj2f0JRHJjPYWPt8-klFF85EdVffrTXV1MuWS9yFRw

**Comment by hankhank10** [comment]
Thanks. And do you get the same error in a fresh incognito browser window?

**Comment by YU000jp** [comment]
I tried with private browsing.
I did "remove access" on my Spotify account.
Animation6w12

**Pull request merged**
